### ISSUE TITLE
[BUG] k3s binary install on armhf fails with checksum check

### ISSUE THREAD

**Issue by ShaunMaher** [saltstack-formulas/kubernetes-formula#45]
### Formula commit hash / release tag

Latest commit on master branch at time of writing: 60a9972486efabf0611ecbeeecf53028b1aad5f1

### Versions reports (master & minion)

Master:
```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-86-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```

Minion:
```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: armv7l
       release: 5.4.159-odroidxu4
        system: Linux
       version: Ubuntu 20.04 focal
```

### Pillar / config used

No relevant pillars.  Using the defaults.

---

### Describe the bug

First up, I 100% realise that using this formula on armhf is a bit of an edge case so I understand if this bug doesn't go straight to the top of the triage queue.

When installing the "kubernetes.k3s" state from this formula on armhf hardware (odroid HC1), the checksum check against the downloaded binary fails.  I assume that this is because the checksum in kubernetes/defaults.yaml is for the AMD64 binary.

```
          ID: kubernetes-k3s-binary-install
    Function: file.managed
        Name: /usr/local/k8s-k3s-v1.21.4+k3s1/bin/k3s
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "Specified sha256 checksum for /usr/local/k8s-k3s-v1.21.4+k3s1/bin/k3s (47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5) does not match actual checksum (208bef525bf968b6b55a2fcb358cf626464e978c99111a1c444f6fad3dd44e06)"
              Attempt 2: Returned a result of "False", with the following comment: "Specified sha256 checksum for /usr/local/k8s-k3s-v1.21.4+k3s1/bin/k3s (47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5) does not match actual checksum (208bef525bf968b6b55a2fcb358cf626464e978c99111a1c444f6fad3dd44e06)"
              Specified sha256 checksum for /usr/local/k8s-k3s-v1.21.4+k3s1/bin/k3s (47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5) does not match actual checksum (208bef525bf968b6b55a2fcb358cf626464e978c99111a1c444f6fad3dd44e06)
     Started: 19:43:27.718853
    Duration: 139117.307 ms
     Changes:
```

### Steps to reproduce the bug

* Add this formula to your gitfs_remotes on the salt master
* On armhf hardware "salt-call state.apply kubernetes.k3s"

### Expected behaviour

Binary is downloaded and checksum check passes.

### Attempts to fix the bug

None yet.  I'm running out of time for today.  Will fork this repo and try a few things over the next few days as time allows.

My first instinct is to replace the hard coded source_hash with the URL to one of the hash files on GitHub which might make future maintenance easier.  WDYT?

**Comment by rmsc** [comment]
I don't think this specific to armhf. I see the same issue when installing a different version in x86_64:

```
ID: kubernetes-k3s-binary-install
    Function: file.managed
        Name: /usr/local/k8s-k3s-v1.23.8+k3s2/bin/k3s
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "Specified sha256 checksum for /usr/local/k8s-k3s-v1.23.8+k3s2/bin/k3s (47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5) does not match actual checksum (ac98439485048f180bd541d10d736765d8e6834232eaf9fea35fd15ba15873b7)"
              Attempt 2: Returned a result of "False", with the following comment: "Specified sha256 checksum for /usr/local/k8s-k3s-v1.23.8+k3s2/bin/k3s (47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5) does not match actual checksum (ac98439485048f180bd541d10d736765d8e6834232eaf9fea35fd15ba15873b7)"
              Specified sha256 checksum for /usr/local/k8s-k3s-v1.23.8+k3s2/bin/k3s (47e686ad5390670da79a467ba94399d72e472364bc064a20fecd3937a8d928b5) does not match actual checksum (ac98439485048f180bd541d10d736765d8e6834232eaf9fea35fd15ba15873b7)
     Started: 18:42:05.674989
    Duration: 137775.31 ms
     Changes:
```

The 'expected' checksum is suspiciously similar to yours, so I suspect it's hardcoded somewhere. Will check.
